name: momo react client CI/CD
on: push

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    env:
      AZURE_WEBAPP_NAME: moomoo    
      AZURE_WEBAPP_PACKAGE_PATH: '.'     
      NODE_VERSION: '14.x'   
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build
      run: |
        npm install
        CI='' npm run build --if-present
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: node-app

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'moomoo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .

        
        
        
